## Introduction to Numpy

[Numpy](http://www.numpy.org/) stands for Numerical Python. Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you know MATLAB, check this [tutorial](https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html) as a stepping stone to learning Numpy. 

## Numpy Arrays

A numpy array is a grid of elements (i.e. matrix) with the same type. 

Syntax to initialize arrays:
```python
import numpy as np
A = np.array(list)
```

The shape of an array is a tuple of integers giving the size of the array. numpy arrays can be initialized from nested lists, and access elements using square brackets

In [1]:
    import numpy as np   # Must import numpy library to use it

A = None # Create a (3,) array
print("The array, A: \n", A)

print()
print("The array, A, has type:", None)
print("The array, A, has shape (i.e. size):", None)    
print("Access individual elements of array A, A[0]=%i, A[1]=%i, A[2]=%i", None ) 


The array, A: 
 None

The array, A, has type: None
The array, A, has shape (i.e. size): None
Access individual elements of array A, A[0]=%i, A[1]=%i, A[2]=%i None


In [2]:
None               
print("Change an element of an array:\n", None) 


Change an element of an array:
 None


In [3]:
B = None  # Create a rank 2x3 array

print("The array, B: \n", None)
print()
print("The array, B, has shape (i.e. size):", None)                    
print("Access individual elements of array B, B[0,0]=%i, B[0,1]=%i, B[1, 0]=%i", None) 


The array, B: 
 None

The array, B, has shape (i.e. size): None
Access individual elements of array B, B[0,0]=%i, B[0,1]=%i, B[1, 0]=%i None


## Array Slicing

**Slicing** - A subset of an array. Arrays can be multidimensional, So you must specify a slice for each dimension of the array

https://docs.scipy.org/doc/numpy/reference/generated/numpy.copy.html


In [4]:
# Create an array with shape (3, 3)
A = None
print("Array A:\n", A)

# Use slicing to pull out the subarray consisting of the first 2 rows
# and column 1; b is the following array of shape (2, 1):
print()
b = None
print("Array b:\n", b)


Array A:
 None

Array b:
 None


In [5]:
# A slice of an array is a view into the same data, If the slice is modified,
# this will modify the original array.
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = A[:2, 1]
print("Value at A[0, 1] is", A[0, 1])   # Prints "2"

b[0] = 10     # b[0] is the same piece of data as a[0, 1]
print("Value at A[0, 1] has changed to", A[0, 1])   # Prints "77"


Value at A[0, 1] is 2
Value at A[0, 1] has changed to 10


In [6]:
# A way to get around this is to make a copy of array A 
# Create an array x, with a reference y and a copy z:

x = A
y = np.copy(A)   # Same as    np.array(A, copy=True)  

# Note that, when we modify x, y changes, but not z:
print()
print("Value at A[2, 1] is", A[2, 1])  

A[2, 1] = 10
print("Value at x[2, 1] is", x[2, 1])  
print("Value at y[2, 1] is", y[2, 1])  
 


Value at A[2, 1] is 8
Value at x[2, 1] is 10
Value at y[2, 1] is 8


In [7]:
A = np.array([[1,2], [3, 4], [5, 6]])

bool_mask = None   # Find the elements of a that are bigger than 3;
                      # this returns a numpy array of Booleans of the same
                      # shape as A, where each slot of bool_idx tells
                      # whether that element of A is > 3.

print("Boolean mask:\n", bool_mask)      

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print("Slice of array A indexed with a bool_mask:\n" , None)  

# We can do all of the above in a single concise statement:
print("A quicker way is to not declare a mask variable:\n", None)   


Boolean mask:
 None
Slice of array A indexed with a bool_mask:
 None
A quicker way is to not declare a mask variable:
 None


In [8]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# Elementwise addition
print("Addition:\n", x + y)

# Elementwise subtraction
print("Subtraction:\n", x - y)

# Elementwise product
print("Multiply:\n", x * y)

# Elementwise division; both produce the array
print("Divide:\n", x / y)

# Elementwise square root; produces the array
print("Square root:\n", np.sqrt(x))


Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiply:
 [[ 5 12]
 [21 32]]
Divide:
 [[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
Square root:
 [[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


## Numpy functions

Some functions that might be useful for you:

- [numpy.zeros](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html), return a new array of given shape and type, filled with zeros.
- [numpy.ones](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html), return a new array of given shape and type, filled with ones.
- [numpy.eye](https://docs.scipy.org/doc/numpy/reference/generated/numpy.eye.html), return a 2-D array with ones on the diagonal and zeros elsewhere.
- [numpy.random.random](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.random.html), return random floats in the interval \[0.0, 1.0). The results are from the “continuous uniform” distribution over the stated interval
- [numpy.T](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.T.html), returns the transpose of a matrix. Same as [self.transpose()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html), except that self is returned if self.ndim < 2.
- [numpy.roll](https://docs.scipy.org/doc/numpy/reference/generated/numpy.roll.html), Roll array elements along a given axis. Elements that roll beyond the last position are re-introduced at the first.



In [9]:
A = None
print("An array of all zeros:\n", A)           

B = None
print("An array of all ones:\n", B)              

C = None
print("A 2x2 identity matrix:\n", C)              

D = None
print("An array filled with random values:\n", D)                     

E = None
print("Transpose of an array:\n", E)  

F = None
print("Roll a vector in one position:\n", F)  
print("Roll a vector in one position:\n", None)  


An array of all zeros:
 None
An array of all ones:
 None
A 2x2 identity matrix:
 None
An array filled with random values:
 None
Transpose of an array:
 None
Roll a vector in one position:
 None
Roll a vector in one position:
 None


## (R,1) versus (R,)
For more information, read this: [stackoverflow](https://stackoverflow.com/questions/22053050/difference-between-numpy-array-shape-r-1-and-r)

In [10]:
np.random.seed(1)  # makes random numbers predictable
A = np.random.randn(4) 
print("Array A:\n", A)
print("Array A has shape:\n", A.shape)
print("Results of dot product of A and A.T (transpose):\n", np.dot(A.T,A)) 
print("Results of dot product of A.T and A (transpose):\n", np.dot(A,A.T)) 

Array A:
 [ 1.62434536 -0.61175641 -0.52817175 -1.07296862]
Array A has shape:
 (4,)
Results of dot product of A and A.T (transpose):
 4.44297083412
Results of dot product of A.T and A (transpose):
 4.44297083412


In [11]:
# recommendation. Have arrays and vectors explicit and not (m,) instead have the shape be (m,1) or (1,n)
np.random.seed(1) 
A = np.random.randn(4,1) # column vector
print("Array A:\n", A)
print("Array A.T (transpose):\n", A.T)

print("Inner product:\n", np.dot(A.T,A))
print("Outer product:\n", np.dot(A,A.T))

Array A:
 [[ 1.62434536]
 [-0.61175641]
 [-0.52817175]
 [-1.07296862]]
Array A.T (transpose):
 [[ 1.62434536 -0.61175641 -0.52817175 -1.07296862]]
Inner product:
 [[ 4.44297083]]
Outer product:
 [[ 2.63849786 -0.99370369 -0.85793334 -1.74287161]
 [-0.99370369  0.37424591  0.32311246  0.65639544]
 [-0.85793334  0.32311246  0.2789654   0.56671172]
 [-1.74287161  0.65639544  0.56671172  1.15126166]]


In [12]:
np.random.seed(1) 
A = np.random.randn(4) 

A_column = np.reshape(A,(4,1))
print("A as a column vector:\n", A_column)

A_row = np.reshape(A,(1,4))
print("A as a column vector:\n", A_row)

A as a column vector:
 [[ 1.62434536]
 [-0.61175641]
 [-0.52817175]
 [-1.07296862]]
A as a column vector:
 [[ 1.62434536 -0.61175641 -0.52817175 -1.07296862]]
